// AUTO-GENERATED by dsl/grammar/generate.mjs — do not edit. Source: dsl/grammar/vocab.json
module.exports = function (hljs) {
  const KEYWORDS = "Rule Let Require if otherwise in for return throw assert builtin array map";
  const TYPES = "void bool byte int int32 int64 uint32 uint256 Hash Block BlockHeader Transaction Timestamp OpCode OutPoint Bits";

  return {
    name: 'Hornet DSL',
    case_insensitive: false,
    keywords: {
      $pattern: /[A-Za-z_][A-Za-z0-9_]*/,
      keyword: KEYWORDS,
      type: TYPES,
    },
    contains: [
      hljs.COMMENT('//', '$'),
      { className: 'number', begin: /\b\d{1,3}(?:,\d{3})*\b/ },
      { className: 'operator', begin: /\|->|->|==|!=|<=|>=|⎧|⎨|⎩|≤|≥|⧺|∈|∀|Σ|↦|←/ },
      // function-call names: CamelCase immediately before '('
      { className: 'title.function', begin: /\b[A-Z][A-Za-z0-9_]*(?=\s*\()/ },
      { className: 'property', begin: /\.[a-z][A-Za-z0-9_]*/ },
      // lowercase identifiers that are not keywords/types
      { className: 'variable', begin: /\b(?!(?:Rule\b|Let\b|Require\b|if\b|otherwise\b|in\b|for\b|return\b|throw\b|assert\b|builtin\b|array\b|map\b|void\b|bool\b|byte\b|int\b|int32\b|int64\b|uint32\b|uint256\b|Hash\b|Block\b|BlockHeader\b|Transaction\b|Timestamp\b|OpCode\b|OutPoint\b|Bits\b))[a-z][A-Za-z0-9_]*/ },
    ],
  };
};
