#!/usr/bin/env node
// Generates BOTH Hornet DSL grammars from a single vocabulary, so the VS Code
// TextMate grammar and the highlight.js grammar can never drift apart.
//
//   Edit  dsl/grammar/vocab.json   then run:  node dsl/grammar/generate.mjs
//
// Outputs:
//   - dsl/syntaxes/hornetdsl.tmLanguage.json   (VS Code editor + markdown injection)
//   - tools/docgen/hornet-dsl.js               (highlight.js: docgen + Marp deck)

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
const vocab = JSON.parse(readFileSync(resolve(here, 'vocab.json'), 'utf8'))

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const wordAlt = (arr) => arr.map(escapeRe).join('|')
// operators: longest first so e.g. |-> wins over ->
const opAlt = [...vocab.operators].sort((a, b) => b.length - a.length).map(escapeRe).join('|')
const NUMBER = '\\b\\d{1,3}(?:,\\d{3})*\\b'
const IDENT = '[A-Za-z_][A-Za-z0-9_]*'

const banner = 'AUTO-GENERATED by dsl/grammar/generate.mjs — do not edit. Source: dsl/grammar/vocab.json'

// ---------- TextMate grammar (VS Code) ----------
const tmGrammar = {
  information_for_contributors: [banner],
  name: 'HornetDSL',
  scopeName: 'source.hornetdsl',
  fileTypes: ['hornet'],
  patterns: [
    { include: '#comments' },
    { include: '#keywords' },
    { include: '#types' },
    { include: '#functions' },
    { include: '#operators' },
    { include: '#numbers' },
  ],
  repository: {
    comments: { patterns: [{ match: '//.*$', name: 'comment.line.double-slash.hornetdsl' }] },
    keywords: { patterns: [{ match: `\\b(${wordAlt(vocab.keywords)})\\b`, name: 'keyword.control.hornetdsl' }] },
    types: { patterns: [{ match: `\\b(${wordAlt(vocab.types)})\\b`, name: 'storage.type.hornetdsl' }] },
    functions: { patterns: [{ match: '\\b[A-Z][A-Za-z0-9_]*\\b(?=\\s*\\()', name: 'entity.name.function.hornetdsl' }] },
    operators: { patterns: [{ match: `(${opAlt})`, name: 'keyword.operator.hornetdsl' }] },
    numbers: { patterns: [{ match: NUMBER, name: 'constant.numeric.hornetdsl' }] },
  },
}
writeFileSync(
  resolve(repo, 'dsl/syntaxes/hornetdsl.tmLanguage.json'),
  JSON.stringify(tmGrammar, null, 2) + '\n',
)

// ---------- highlight.js grammar (docgen + Marp) ----------
const negLookahead = [...vocab.keywords, ...vocab.types].map((w) => escapeRe(w) + '\\b').join('|')
const hljs = `// ${banner}
module.exports = function (hljs) {
  const KEYWORDS = ${JSON.stringify(vocab.keywords.join(' '))};
  const TYPES = ${JSON.stringify(vocab.types.join(' '))};

  return {
    name: 'Hornet DSL',
    case_insensitive: false,
    keywords: {
      $pattern: /${IDENT}/,
      keyword: KEYWORDS,
      type: TYPES,
    },
    contains: [
      hljs.COMMENT('//', '$'),
      { className: 'number', begin: /${NUMBER}/ },
      { className: 'operator', begin: /${opAlt}/ },
      // function-call names: CamelCase immediately before '('
      { className: 'title.function', begin: /\\b[A-Z][A-Za-z0-9_]*(?=\\s*\\()/ },
      { className: 'property', begin: /\\.[a-z][A-Za-z0-9_]*/ },
      // lowercase identifiers that are not keywords/types
      { className: 'variable', begin: /\\b(?!(?:${negLookahead}))[a-z][A-Za-z0-9_]*/ },
    ],
  };
};
`
writeFileSync(resolve(repo, 'tools/docgen/hornet-dsl.js'), hljs)

console.log('Generated:')
console.log('  dsl/syntaxes/hornetdsl.tmLanguage.json')
console.log('  tools/docgen/hornet-dsl.js')
console.log(`  (${vocab.keywords.length} keywords, ${vocab.types.length} types, ${vocab.operators.length} operators)`)
